version: '2.1'

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "4567:4567"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orders" ]
      interval: 5s
      retries: 5
    env_file:
      - .env



volumes:
  postgres_data:
